using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DangerousPanel_Server
{
    public static class ScancodeConvert
    {
        public static Dictionary<string, ushort> mapping = new Dictionary<string, ushort>()
        {
            { "ESC", 0x01 },
            { "1", 0x02 },
            { "2", 0x03 },
            { "3", 0x04 },
            { "4", 0x05 },
            { "5", 0x06 },
            { "6", 0x07 },
            { "7", 0x08 },
            { "8", 0x09 },
            { "9", 0x0A },
            { "0", 0x0B },
            { "-", 0x0C },
            { "=", 0x0D },
            { "BACK", 0x0E },
            { "TAB", 0x0F },
            { "Q", 0x10 },
            { "W", 0x11 },
            { "E", 0x12 },
            { "R", 0x13 },
            { "T", 0x14 },
            { "Y", 0x15 },
            { "U", 0x16 },
            { "I", 0x17 },
            { "O", 0x18 },
            { "P", 0x19 },
            { "[", 0x1A },
            { "]", 0x1B },
            { "ENTER", 0x1C },
            { "LCTRL", 0x1D },
            { "A", 0x1E },
            { "S", 0x1F },
            { "D", 0x20 },
            { "F", 0x21 },
            { "G", 0x22 },
            { "H", 0x23 },
            { "J", 0x24 },
            { "K", 0x25 },
            { "L", 0x26 },
            { ";", 0x27 },
            { "'", 0x28 },
            { "`", 0x29 },
            { "LSHIFT", 0x2A },
            { "\\", 0x2B },
            { "Z", 0x2C },
            { "X", 0x2D },
            { "C", 0x2E },
            { "V", 0x2F },
            { "B", 0x30 },
            { "N", 0x31 },
            { "M", 0x32 },
            { ",", 0x33 },
            { ".", 0x34 },
            { "/", 0x35 },
            { "RSHIFT", 0x36 },
            { "*", 0x37 },
            { "LALT", 0x38 },
            { " ", 0x39 },
            { "CAPS", 0x3A },
            { "F1", 0x3B },
            { "F2", 0x3C },
            { "F3", 0x3D },
            { "F4", 0x3E },
            { "F5", 0x3F },
            { "F6", 0x40 },
            { "F7", 0x41 },
            { "F8", 0x42 },
            { "F9", 0x43 },
            { "F10", 0x44 },
            { "NUM", 0x45 },
            { "SCRL", 0x46 },
            { "N7", 0x47 },
            { "N8", 0x48 },
            { "N9", 0x49 },
            { "N-", 0x4A },
            { "N4", 0x4B },
            { "N5", 0x4C },
            { "N6", 0x4D },
            { "+", 0x4E },
            { "N1", 0x4F },
            { "N2", 0x50 },
            { "N3", 0x51 },
            { "N0", 0x52 },
            { "N.", 0x53 },
            { "F11", 0x57 },
            { "F12", 0x58 },
            { "F13", 0x64 },
            { "F14", 0x65 },
            { "F15", 0x66 },
            { "KANA", 0x70 },
            { "CONVERT", 0x79 },
            { "NOCONVERT", 0x7B },
            { "¥", 0x7D },
            { "N=", 0x8D },
            { "^", 0x90 },
            { "@", 0x91 },
            { ":", 0x92 },
            { "_", 0x93 },
            { "KANJI", 0x94 },
            { "STOP", 0x95 },
            { "AX", 0x96 },
            { "UNLABELED", 0x97 },
            { "NPENTER", 0x9C },
            { "RCTRL", 0x9D },
            { "N,", 0xB3 },
            { "N/", 0xB5 },
            { "SYSRQ", 0xB7 },
            { "RALT", 0xB8 },
            { "PAUSE", 0xC5 },
            { "HOME", 0xC7 },
            { "UP", 0xC8 },
            { "PGUP", 0xC9 },
            { "LEFT", 0xCB },
            { "RIGHT", 0xCD },
            { "END", 0xCF },
            { "DOWN", 0xD0 },
            { "PGDOWN", 0xD1 },
            { "INSERT", 0xD2 },
            { "DEL", 0xD3 },
            { "LWIN", 0xDB },
            { "RWIN", 0xDC },
            { "MENU", 0xDD },
            { "POWER", 0xDE },
            { "SLEEP", 0xDF }
        };

        public static ushort GetScancode(string key)
        {
            return mapping[key.ToUpper()];
        }
    }
}
